items:
  - name: gomo
    directory: /Users/lukevan/Code/fieldwork-web
    command: yarn dev
  - name: gmt
    directory: /Users/lukevan/Code/gm-tracker
    command: uv run main.py
  - name: spanish
    directory: /Users/lukevan/Code/spanish-bot
    command: uv run main.py
